### ISSUE TITLE
#02. OpenAPI 연동

### ISSUE THREAD

**Issue by akariyan** [akariyan/NextJSQuizApp#5]
목표 : 옵션에 따라 퀴즈 목록을 제공하는 OpenAPI 연동

작업 목록 : 
- API로 퀴즈 목록을 가공하는 Component 작성

기한 : ~21/09/28/화

**Comment by ppark2ya** [comment]
### 리뷰

- src/types/QuizAPIResponse.ts : src/types 안에는 글로벌 타입들을 넣는게 좋고 API response 에 대한 type은 QuizAPI.ts 안에 같이 넣거나 api 디렉토리 안에 types 를 따로 만들어서 관리하는게 좋아보임
- styles 안에 있는 css 파일 걷어내고 stitchjs의 globalcss 로 적용필요
- axios는 글로벌로 url, header등 설정하는게 관리에 용이함. [참고](https://github.com/ppark2ya/quiz-webapp/tree/main/src/api)
- pracswr.tsx
  - hook의 경우 네이밍 컨벤션이 use~.ts 임(ex. usePracSwr.ts)
  - api fetch하는 부분을 QuizAPI.ts 에서 정의한 axios 함수로 받아서 적용 필요
  - hook에서는 component 렌더링을 하지 않고 데이터만 다룸. return { data, error }; 로 바꾸고 컴포넌트에서 데이터 받아서 렌더링 처리
